### ISSUE TITLE
Fixed wrong instruction information ('slti')

### ISSUE THREAD

**Issue by rlj1202** [sslab-ajou/sce212-pa2-2019f#2]
#1 

⊂_ヽ
　 ＼＼ Λ＿Λ
　　 ＼( ‘ㅅ' ) 두둠칫
　　　 >　⌒ヽ
　　　/ 　 へ＼
　　 /　　/　＼＼
　　 ﾚ　ノ　　 ヽ_つ
　　/　/두둠칫
　 /　/|
　(　(ヽ
　|　|、＼
　| 丿 ＼ ⌒)
　| |　　) /
`ノ )　　Lﾉ

**Comment by beowulf** [comment]
Watch를 안걸어놨더니 notification이 안오고 있었네요. 처리가 늦어져서 미안해요.
